New types conversion
eProsima/FastDDS-SH pull request #43
Opened 2020-03-03 14:46 UTC by LuisGP

This PR adds support for the conversion of the `map`, `union` types, and resolves the `alias` type.

2020-03-03 14:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=soss-dds-linux&build=30)](http://jenkins.eprosima.com:8080/job/soss-dds-linux/30/)

2020-03-05 06:50 UTC, richiware submitted a review, later dismissed

2020-03-05 06:50 UTC, richiware commented on packages/dds/src/Conversion.cpp
> +            }
And for UNION_TYPE?

2020-03-05 06:56 UTC, jamoralp requested changes

2020-03-05 06:56 UTC, jamoralp commented on packages/dds/src/Conversion.cpp
> +            }
`xtypes::TypeKind::UNION_TYPE` case missing

2020-03-05 07:14 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=soss-dds-linux&build=31)](http://jenkins.eprosima.com:8080/job/soss-dds-linux/31/)

2020-03-05 07:42 UTC, jamoralp approved these changes
LGTM

2020-03-05 07:44 UTC, merged